export const pcbVertexShader = [
  'varying vec2 vUv;',
  'void main() {',
  '  vUv = uv;',
  '  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);',
  '}',
].join('\n');

// Procedural PCB field: traces and signal packets are generated in shader space.
export const pcbFragmentShader = [
  'uniform float uTime;',
  'uniform vec2 uMouse;',
  'varying vec2 vUv;',
  'float line(float value, float position, float width) { return 1.0 - smoothstep(width, width + 0.003, abs(value - position)); }',
  'float segment(vec2 uv, float row, float start, float end) { float y = line(uv.y, row, 0.004); return y * step(start, uv.x) * step(uv.x, end); }',
  'void main() {',
  '  vec2 uv = vUv;',
  '  vec3 base = vec3(0.043, 0.059, 0.051);',
  '  vec3 copper = vec3(1.0, 0.54, 0.24);',
  '  vec3 cyan = vec3(0.298, 0.878, 0.824);',
  '  float traces = 0.0;',
  '  for (int i = 0; i < 9; i++) {',
  '    float row = 0.09 + float(i) * 0.105;',
  '    float offset = mod(float(i) * 0.137, 0.27);',
  '    traces += segment(uv, row, 0.03 + offset, 0.38 + offset);',
  '    traces += segment(uv, row + 0.034, 0.53 - offset, 0.94 - offset * 0.3);',
  '    float viaX = 0.32 + mod(float(i) * 0.17, 0.48);',
  '    traces += line(uv.x, viaX, 0.003) * step(row, uv.y) * step(uv.y, row + 0.095);',
  '  }',
  '  float packet = 0.0;',
  '  for (int i = 0; i < 6; i++) {',
  '    float row = 0.09 + float(i) * 0.16;',
  '    float travel = fract(uTime * 0.08 + float(i) * 0.19);',
  '    float x = 0.08 + travel * 0.8;',
  '    packet += exp(-2300.0 * ((uv.x - x) * (uv.x - x) + (uv.y - row) * (uv.y - row)));',
  '  }',
  '  float mouseGlow = exp(-20.0 * dot(uv - uMouse, uv - uMouse));',
  '  vec3 color = base + copper * traces * 0.55 + copper * packet * 1.4 + cyan * mouseGlow * traces * 0.42;',
  '  color += vec3(0.03) * sin((uv.x + uv.y + uTime * 0.02) * 90.0);',
  '  gl_FragColor = vec4(color, 1.0);',
  '}',
].join('\n');
